#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Feb 23, 2019 10:30:39 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

import Login_GUI_support
from icon import icon

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Login_GUI_support.set_Tk_var()
    top = LoginGUI (root)
    Login_GUI_support.init(root, top)
    root.mainloop()

w = None
def create_LoginGUI(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    Login_GUI_support.set_Tk_var()
    top = LoginGUI (w)
    Login_GUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_LoginGUI():
    global w
    w.destroy()
    w = None

class LoginGUI:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#fffffb'  # 'white'
        _fgcolor = '#130c0e'  # 'black'
        _compcolor = '#d3c6a6' # 'sandy' 
        _ana2color = '#d3d7d4' # 'milkiness' 
        font10 = "-family 微软雅黑 -size 11 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        font9 = "-family 微软雅黑 -size 17 -weight bold -slant italic "  \
            "-underline 0 -overstrike 0"

        sw = top.winfo_screenwidth()
        sh = top.winfo_screenheight()
        w = (sw - 500)//2
        h = (sh - 330)//2
        top.geometry("500x330+%s+%s" %(w, h))
        top.title("用户登录界面 - 医院数据安全系统")
        with open('icon.ico', 'wb') as ico:
            import base64, os
            ico.write(base64.b64decode(icon))
        top.iconbitmap(bitmap="icon.ico")
        os.remove('icon.ico')
        top.resizable(False, False)
        top.configure(background="#fffffb")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.AccountEntry = tk.Entry(top)
        self.AccountEntry.place(relx=0.4, rely=0.394,height=27, relwidth=0.308)
        self.AccountEntry.configure(background="#fffffb")
        self.AccountEntry.configure(disabledforeground="#a3a3a3")
        self.AccountEntry.configure(font=font10)
        self.AccountEntry.configure(foreground="#130c0e")
        self.AccountEntry.configure(highlightbackground="#d3d7d4")
        self.AccountEntry.configure(highlightcolor="#130c0e")
        self.AccountEntry.configure(insertbackground="black")
        self.AccountEntry.configure(selectbackground="#d3d7d4")
        self.AccountEntry.configure(selectforeground="#130c0e")
        self.AccountEntry.configure(textvariable=Login_GUI_support.account)
        self.AccountEntry.bind("<Key-Return>", Login_GUI_support.login)

        self.PasswdEntry = tk.Entry(top)
        self.PasswdEntry.place(relx=0.4, rely=0.576,height=27, relwidth=0.308)
        self.PasswdEntry.configure(background="#fffffb")
        self.PasswdEntry.configure(disabledforeground="#a3a3a3")
        self.PasswdEntry.configure(font=font10)
        self.PasswdEntry.configure(foreground="#130c0e")
        self.PasswdEntry.configure(highlightbackground="#d3d7d4")
        self.PasswdEntry.configure(highlightcolor="#130c0e")
        self.PasswdEntry.configure(insertbackground="black")
        self.PasswdEntry.configure(selectbackground="#d3d7d4")
        self.PasswdEntry.configure(selectforeground="#130c0e")
        self.PasswdEntry.configure(show="*")
        self.PasswdEntry.configure(textvariable=Login_GUI_support.passwd)
        self.PasswdEntry.bind("<Key-Return>", Login_GUI_support.login)

        self.AccountLabel = tk.Label(top)
        self.AccountLabel.place(relx=0.28, rely=0.394, height=28, width=46)
        self.AccountLabel.configure(activebackground="#f9f9f9")
        self.AccountLabel.configure(activeforeground="black")
        self.AccountLabel.configure(background="#fffffb")
        self.AccountLabel.configure(disabledforeground="#a3a3a3")
        self.AccountLabel.configure(font=font10)
        self.AccountLabel.configure(foreground="#130c0e")
        self.AccountLabel.configure(highlightbackground="#d9d9d9")
        self.AccountLabel.configure(highlightcolor="black")
        self.AccountLabel.configure(text='''帐号''')

        self.PasswdLabel = tk.Label(top)
        self.PasswdLabel.place(relx=0.28, rely=0.576, height=28, width=46)
        self.PasswdLabel.configure(activebackground="#f9f9f9")
        self.PasswdLabel.configure(activeforeground="black")
        self.PasswdLabel.configure(background="#fffffb")
        self.PasswdLabel.configure(disabledforeground="#a3a3a3")
        self.PasswdLabel.configure(font=font10)
        self.PasswdLabel.configure(foreground="#130c0e")
        self.PasswdLabel.configure(highlightbackground="#d9d9d9")
        self.PasswdLabel.configure(highlightcolor="black")
        self.PasswdLabel.configure(text='''口令''')

        self.LoginButton = tk.Button(top)
        self.LoginButton.place(relx=0.44, rely=0.758, height=29, width=85)
        self.LoginButton.configure(activebackground="#d3d7d4")
        self.LoginButton.configure(activeforeground="#130c0e")
        self.LoginButton.configure(background="#f6f5ec")
        self.LoginButton.configure(command=Login_GUI_support.login)
        self.LoginButton.configure(cursor="hand2")
        self.LoginButton.configure(disabledforeground="#a3a3a3")
        self.LoginButton.configure(font=font10)
        self.LoginButton.configure(foreground="#130c0e")
        self.LoginButton.configure(highlightbackground="#d3d7d4")
        self.LoginButton.configure(highlightcolor="#130c0e")
        self.LoginButton.configure(pady="0")
        self.LoginButton.configure(text='''登录''')
        self.LoginButton.bind("<Key-Return>", Login_GUI_support.login)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Title = tk.Label(top)
        self.Title.place(relx=0.28, rely=0.152, height=38, width=216)
        self.Title.configure(activebackground="#f9f9f9")
        self.Title.configure(activeforeground="black")
        self.Title.configure(background="#fffffb")
        self.Title.configure(disabledforeground="#a3a3a3")
        self.Title.configure(font=font9)
        self.Title.configure(foreground="#3e4145")
        self.Title.configure(highlightbackground="#d9d9d9")
        self.Title.configure(highlightcolor="black")
        self.Title.configure(text='''医院数据安全系统''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="???? 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





